config/routes.rb
Libexpo::Application.routes.draw do

  resources :publications

  resources :notes

  resources :events

  get 'search/show'

  resources :photos

  resources :nodes

  get 'tags/:tag', to: 'tags#index', as: :tag

  resources :comments

  resources :books

  resources :articles

  resources :collections

  resources :categories

  mount Rich::Engine => '/rich', :as => 'rich'

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  devise_for :users

  get 'authors/:id', to: 'authors#show'

  root :to => 'welcome#index'

end

app/models/note.rb
class Note < ActiveRecord::Base
  belongs_to :user
  belongs_to :author
  belongs_to :collection
  belongs_to :article
  belongs_to :book
  belongs_to :publication, :inverse_of => :notes

  attr_accessible :title, :description, :is_public
  attr_accessible :user_id, :author_id, :publication_id, :collection_id, :article_id, :book_id

  validates :user, :presence => true
  validates :title, :presence => true, :uniqueness => true, :length => {:maximum => 255}

  rails_admin do
    configure :user do
      def render
        bindings[:view].render :partial => 'rails_admin/main/global_edit_user', :locals => {:field => self, :form => bindings[:form]}
      end
    end
    configure :author do
      def render
        bindings[:view].render :partial => 'shared/author', :locals => {:field => self, :form => bindings[:form]}
      end
    end
    configure :publication
    configure :collection do
      hide
    end
    configure :article do
      hide
    end
    configure :book do
      inverse_of :note
    end
    configure :title do
      def render
        bindings[:view].render :partial => 'shared/title', :locals => {:field => self, :form => bindings[:form]}
      end
    end
    configure :description, :rich_editor do
      config({
                 :toolbar => Editor::TOOLBAR,
                 :stylesSet => Editor::STYLESET,
                 :width => '99%', :height => '200px'
             })
    end
    configure :updated_at do
      date_format :long
      read_only true
    end
    list do
      field :publication
      field :book
      field :title
      field :is_public
      field :updated_at
      items_per_page 10
    end
    show do
      field :publication
      field :book
      field :title
      field :is_public
      field :description do
        pretty_value do
          bindings[:object].description.html_safe
        end
      end
      field :updated_at
    end
  end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController

  load_and_authorize_resource

  # GET /notes
  # GET /notes.json
  def index
    @notes = Note.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @notes }
    end
  end

  # GET /notes/1
  # GET /notes/1.json
  def show
    @note = Note.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @note }
    end
  end

  # GET /notes/new
  # GET /notes/new.json
  def new
    @note = Note.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @note }
    end
  end

  # GET /notes/1/edit
  def edit
    @note = Note.find(params[:id])
  end

  # POST /notes
  # POST /notes.json
  def create
    @note = Note.new(params[:note])

    respond_to do |format|
      if @note.save
        format.html { redirect_to @note, notice: 'Note was successfully created.' }
        format.json { render json: @note, status: :created, location: @note }
      else
        format.html { render action: "new" }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /notes/1
  # PUT /notes/1.json
  def update
    @note = Note.find(params[:id])

    respond_to do |format|
      if @note.update_attributes(params[:note])
        format.html { redirect_to @note, notice: 'Note was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notes/1
  # DELETE /notes/1.json
  def destroy
    @note = Note.find(params[:id])
    @note.destroy

    respond_to do |format|
      format.html { redirect_to notes_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/notes/_form.html.haml
= form_for @note do |f|
  - if @note.errors.any?
    #error_explanation
      %h2= "#{pluralize(@note.errors.count, "error")} prohibited this note from being saved:"
      %ul
        - @note.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :user
    = f.text_field :user
  .field
    = f.label :collection
    = f.text_field :collection
  .field
    = f.label :article
    = f.text_field :article
  .field
    = f.label :book
    = f.text_field :book
  .field
    = f.label :description
    = f.text_area :description
  .field
    = f.label :is_public
    = f.check_box :is_public
  .actions
    = f.submit 'Save'

app/views/notes/edit.html.haml
%h1 Editing note

= render 'form'

= link_to 'Show', @note
\|
= link_to 'Back', notes_path

app/views/notes/index.html.haml
- if signed_in?
  = link_to (image_tag "edit.png"), "/admin/note"
  = link_to t(:notes_link_to_edit), "/admin/note"

%table
  - @notes.each do |note|
    %tr
      %td
        - if signed_in? && !current_user.customer?
          %p
            = link_to (image_tag "edit.png"), "/admin/note/#{note.id}/edit"
            = link_to t(:note_link_to_edit), "/admin/note/#{note.id}/edit"
            .title= note.title
    %tr
      %td.img= link_to (image_tag note.book.image, alt: note.book.title, data: { ot: "#{image_tag note.book.image.gsub(/thumb/, 'original'), alt: note.book.title}", :'ot-delay' => '0.6', :'ot-background' => '#ffffe1' }), book_path(note.book)
      %td{style: 'vertical-align: top;'}
        %p.dsc= note.description.html_safe
        = render :partial => '/shared/card', :locals => {user: note.user, timestamp: note.updated_at}

app/views/notes/new.html.haml
%h1 New note

= render 'form'

= link_to 'Back', notes_path

app/views/notes/show.html.haml
%p#notice= notice

%p
  %b User:
  = @note.user
%p
  %b Collection:
  = @note.collection
%p
  %b Article:
  = @note.article
%p
  %b Book:
  = @note.book
%p
  %b Description:
  = @note.description
%p
  %b Is public:
  = @note.is_public

= link_to 'Edit', edit_note_path(@note)
\|
= link_to 'Back', notes_path