config/routes.rb
Libexpo::Application.routes.draw do

  resources :publications

  resources :notes

  resources :events

  get 'search/show'

  resources :photos

  resources :nodes

  get 'tags/:tag', to: 'tags#index', as: :tag

  resources :comments

  resources :books

  resources :articles

  resources :collections

  resources :categories

  mount Rich::Engine => '/rich', :as => 'rich'

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  devise_for :users

  get 'authors/:id', to: 'authors#show'

  root :to => 'welcome#index'

end

app/models/node.rb
class Node < ActiveRecord::Base
  has_many :articles, :inverse_of => :node, :dependent => :destroy

  attr_accessible :description, :is_public, :name
  attr_accessible :article_ids

  validates :name, :presence => true, :uniqueness => true, :length => {:maximum => 255}

  extend FriendlyId
  friendly_id :name

  rails_admin do
    configure :description, :rich_editor do
      config({
                 :toolbar => Editor::TOOLBAR,
                 :stylesSet => Editor::STYLESET,
                 :width => '99%', :height => '200px'
             })
    end
    configure :updated_at do
      date_format :long
      read_only true
    end
    configure :slug do
      hide
    end
    list do
      field :is_public
      field :name
      field :updated_at
      items_per_page 10
    end
    show do
      field :is_public
      field :name
      field :description do
        pretty_value do
          bindings[:object].description.html_safe
        end
      end
      field :updated_at
    end
  end
end

app/controllers/nodes_controller.rb
class NodesController < ApplicationController

  load_and_authorize_resource
  skip_authorize_resource :only => :show

  # GET /nodes
  # GET /nodes.json
  def index
    @nodes = Node.where('`is_public`').order('`name` ASC')

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @nodes }
    end
  end

  # GET /nodes/1
  # GET /nodes/1.json
  def show
    @node = Node.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @node }
    end
  end

  # GET /nodes/new
  # GET /nodes/new.json
  def new
    @node = Node.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @node }
    end
  end

  # GET /nodes/1/edit
  def edit
    @node = Node.find(params[:id])
  end

  # POST /nodes
  # POST /nodes.json
  def create
    @node = Node.new(params[:node])

    respond_to do |format|
      if @node.save
        format.html { redirect_to @node, notice: 'Node was successfully created.' }
        format.json { render json: @node, status: :created, location: @node }
      else
        format.html { render action: "new" }
        format.json { render json: @node.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /nodes/1
  # PUT /nodes/1.json
  def update
    @node = Node.find(params[:id])

    respond_to do |format|
      if @node.update_attributes(params[:node])
        format.html { redirect_to @node, notice: 'Node was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @node.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /nodes/1
  # DELETE /nodes/1.json
  def destroy
    @node = Node.find(params[:id])
    @node.destroy

    respond_to do |format|
      format.html { redirect_to nodes_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/nodes_helper.rb
module NodesHelper
end

app/views/nodes/_form.html.haml
= form_for @node do |f|
  - if @node.errors.any?
    #error_explanation
      %h2= "#{pluralize(@node.errors.count, "error")} prohibited this node from being saved:"
      %ul
        - @node.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :description
    = f.text_area :description
  .field
    = f.label :slug
    = f.text_field :slug
  .field
    = f.label :is_public
    = f.check_box :is_public
  .actions
    = f.submit 'Save'

app/views/nodes/edit.html.haml
%h1 Editing node

= render 'form'

= link_to 'Show', @node
\|
= link_to 'Back', nodes_path

app/views/nodes/index.html.haml
%h1 Listing nodes

%table
  %tr
    %th Name
    %th Description
    %th Slug
    %th Is public
    %th
    %th
    %th

  - @nodes.each do |node|
    %tr
      %td= node.name
      %td= node.description
      %td= node.slug
      %td= node.is_public
      %td= link_to 'Show', node
      %td= link_to 'Edit', edit_node_path(node)
      %td= link_to 'Destroy', node, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Node', new_node_path

app/views/nodes/new.html.haml
%h1 New node

= render 'form'

= link_to 'Back', nodes_path

app/views/nodes/show.html.haml
= title @node.name

- if signed_in? && !current_user.customer?
  = link_to (image_tag "edit.png"), "/admin/node/#{@node.id}/edit"
  = link_to t(:node_link_to_edit), "/admin/node/#{@node.id}/edit"

%p.title= @node.name           if signed_in?
%p= @node.description.html_safe