config/routes.rb
Libexpo::Application.routes.draw do

  resources :publications

  resources :notes

  resources :events

  get 'search/show'

  resources :photos

  resources :nodes

  get 'tags/:tag', to: 'tags#index', as: :tag

  resources :comments

  resources :books

  resources :articles

  resources :collections

  resources :categories

  mount Rich::Engine => '/rich', :as => 'rich'

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  devise_for :users

  get 'authors/:id', to: 'authors#show'

  root :to => 'welcome#index'

end

app/views/shared/_auth.html.haml
-if signed_in?
  = link_to (image_tag "process.png"), "/admin", :title => (t :welcome_link_to_dashboard)
  = link_to (t :welcome_link_to_dashboard), "/admin"
  %span.spacer
  = link_to (image_tag "logout.png", class: "image"), "/users/sign_out", :method => :delete, :title => (t :sign_out_title)
  = link_to (t :sign_out_title), "/users/sign_out", :method => :delete, :title => (t :sign_out_title)
  %span.spacer
  = current_user.username

-else
  = image_tag "lock.png", class: "image", :title => (t :not_logged_title)
  = link_to (image_tag "user_accept.png", class: "image"), "/users/sign_in", :title => (t :sign_in_title)
  = link_to (t :sign_in_title), "/users/sign_in", :title => (t :sign_in_title)

app/views/shared/_author.html.haml
- @authors = User.where(role: I18n.t(:app_role_customer))
- if params[:model_name] == 'publication' && params[:id].present?
  - @publication = Publication.find(params[:id])
  - if current_user.customer?
    = render :partial => '/shared/card', :locals => {user: current_user, timestamp: nil}
    = hidden_field_tag 'publication[author_id]', current_user.id
  - else
    = collection_select :publication, :author_id, @authors, :id, :profile_description, include_blank: true
- elsif params[:model_name] == 'note' && params[:id].present?
  - @note = Note.find(params[:id])
  - if current_user.customer?
    = render :partial => '/shared/card', :locals => {user: current_user, timestamp: nil}
    = hidden_field_tag 'note[author_id]', current_user.id
  - else
    = collection_select :note, :author_id, @authors, :id, :profile_description, include_blank: true
- else
  - if current_user.customer?
    = render :partial => '/shared/card', :locals => {user: current_user, timestamp: nil}
    = hidden_field_tag 'note[author_id]', current_user.id
  - elsif params[:model_name] == 'publication'
    = collection_select :publication, :author_id, @authors, :id, :profile_description, include_blank: true
  - elsif params[:model_name] == 'note'
    = collection_select :note, :author_id, @authors, :id, :profile_description, include_blank: true

app/views/shared/_calendar.html.haml
#fc

app/views/shared/_card.html.haml
%table
  %tr
    %td.img= image_tag user.image, alt: user.profile_description, class: 'thumb right', data: { ot: "#{image_tag user.image.gsub(/thumb/, 'original'), alt: user.profile_description}", :'ot-delay' => '0.6', :'ot-background' => '#ffffe1' } if user.image.present?
    %td
      %p.author= user.profile_description
      %p.author= user.title if user.title.present?
      -  unless params[:model_name] == 'publication' || params[:model_name] == 'note' || params[:model_name] == 'collection' || params[:model_name] == 'article' || params[:model_name] == 'book' || params[:model_name] == 'comment' || params[:model_name] == 'photo' || params[:model_name] == 'event'
        %p.date= l timestamp, format: :long
:javascript
  $(function () {
    $('.thumb').css('height', '54px');
  });

app/views/shared/_carousel.html.erb
<div id="carousel_container">
  <canvas width="1143" height="300" id="main_canvas"></canvas>
</div>
<div id="carousel">
  <%- if @photos.present? %>
      <% @photos.each do |book| %>
          <%= link_to image_tag(book.image, class: 'photo', alt: book.title), book_path(book) %>
      <% end %>
  <% end %>
</div>

app/views/shared/_chat.html.haml
:javascript
  function showChatImage(workgroup) {
      var img = "http://help.adidonntu.ru/adichat/live?action=isAvailable&workgroup=library@workgroup.help.adidonntu.ru";
      var gotoURL = "http://help.adidonntu.ru/adichat/start.jsp?workgroup=library@workgroup.help.adidonntu.ru&location=" + window.location.href;
      document.write(
              "<a id=\"liveLink\" href=\"javascript:void(0)\" onclick=\"launchWin(\'framemain\','" + gotoURL + "',600, 400);return false;\"><img id=\"liveImage\" alt='#{t :chat_image_title}' title='#{t :chat_image_title}' src=\"" + img + "\"></a>");
  }
:javascript
  showChatImage('library@workgroup.help.adidonntu.ru');

app/views/shared/_cloud.html.erb
<div id="tags_container">
  <canvas width="300" height="300" id="tag_canvas"></canvas>
</div>
<div id="tags">
  <%- if @tags.present? %>
      <% tag_cloud @tags, %w() do |tag, css_class| %>
          <%= link_to tag.name, tag_path(tag.name), class: css_class %>
      <% end %>
  <% end %>
</div>

app/views/shared/_flash.html.haml
- unless notice.nil?
  .notice= notice
- unless alert.nil?
  .alert= alert

app/views/shared/_footer.html.haml
#menu= render '/shared/links'

app/views/shared/_header.html.haml
#menu= render '/shared/menu'
-#= image_tag "banner.png", id: "banner", alt: "", title: ""

app/views/shared/_links.html.haml
-if signed_in?
  = link_to (image_tag "process.png"), "/admin", :title => (t :welcome_link_to_dashboard)
  = link_to (t :welcome_link_to_dashboard), "/admin"

  = image_tag "footer.png", id: "logo_footer", alt: "", title: ""
-#.field
-#-if devise_mapping.registerable? && controller_name != 'registrations'
-#  = link_to (image_tag "user_add.png"), new_registration_path(@user), :title => (t :sign_up_title)
-#  = link_to (t :sign_up_title), new_registration_path(@user)
-#.field
-#  -if devise_mapping.recoverable? && controller_name != 'passwords'
-#    = link_to (image_tag "help.png"), new_password_path(@user), :title => (t :user_label_forgot_your_password)
-#    = link_to (t :user_label_forgot_your_password), new_password_path(@user)
-#.field
-#  -if controller_name != 'sessions'
-#    = link_to (image_tag "next.png"), new_session_path(resource_name), :title => (t :user_sign_in_page_title)
-#    = link_to (t :user_sign_in_page_title), new_session_path(resource_name)

app/views/shared/_menu.html.haml
= render 'shared/auth'
-#-if signed_in?
-#  %span.spacer
-#  = image_tag "date_time.png", alt: "", title: "", class: "image"
-#  = Time.current.strftime("%F")
-#  %span#clock
-#  = Time.current.strftime("%z")

app/views/shared/_sidebar.html.haml
.bookshelf= render '/shared/bookshelf'
= image_tag "adi-logo.png", id: "logo", alt: "", title: ""
.app= t :app_title

.tree

= render "search/form"
= render "shared/cloud"

:javascript
  $(function () {
    var categories = #{@exhibitions.to_json.html_safe};
    var nodes = #{@branchs.to_json.html_safe};
    $('.tree').jstree({
      "core": {
        "strings": {
          "loading": "#{t(:loading)}"
        }
      },
      "plugins": [ "themes", "json_data", "ui", "cookies" ],
      "cookies": { "cookie_options": { "path": "/" } },
      "themes": {
        "theme": "apple",
        "url": "/assets/themes/apple/style.css",
        "dots": false,
        "icons": true
      },
      "json_data": {
        "data": [ categories, nodes ]
      }
    }).bind("reselect.jstree", function() {
      $('.tree').bind("select_node.jstree", function (e, data) {
        window.location = $.data(data.rslt.obj[0], "href");
      });
    });
  });

app/views/shared/_slideshow.html.erb
<div id="blueimp-image-carousel" class="blueimp-gallery blueimp-gallery-carousel">
  <div class="slides"></div>
  <h3 class="title"></h3>
  <p class="description"></p>
  <a class="prev">‹</a>
  <a class="next">›</a>
  <a class="close">×</a>
  <a class="play-pause"></a>
  <ol class="indicator"></ol>
</div>